//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Client.InterBank {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InterBank.IInterBankOps", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IInterBankOps {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IInterBankOps/PurchaseStock", ReplyAction = "http://tempuri.org/IInterBankOps/PurchaseStockResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        void PurchaseStock(string company, int quantity, string username, string email, DateTime request_date_time, string execution_value);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterBankOps/SellStock", ReplyAction= "http://tempuri.org/IInterBankOps/SellStockResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        void SellStock(string company, int quantity, string username, string email, DateTime request_date_time, string execution_value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInterBankOpsChannel : Client.InterBank.IInterBankOps, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InterBankOpsClient : System.ServiceModel.ClientBase<Client.InterBank.IInterBankOps>, Client.InterBank.IInterBankOps {
        
        public InterBankOpsClient() {
        }
        
        public InterBankOpsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InterBankOpsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterBankOpsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterBankOpsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SellStock(string company, int quantity, string username, string email, DateTime request_date_time, string execution_value) {
            base.Channel.SellStock(company, quantity, username, email, request_date_time, execution_value);
        }

        public void PurchaseStock(string company, int quantity, string username, string email, DateTime request_date_time, string execution_value)
        {
            base.Channel.PurchaseStock(company, quantity, username, email, request_date_time, execution_value);
        }
    }
}
