//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.InterBank {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InterBank.IInterBankOps", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IInterBankOps {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterBankOps/PurchaseStock", ReplyAction= "http://tempuri.org/IInterBankOps/PurchaseStockResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        void PurchaseStock(string company, double amount);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterBankOps/SellStock", ReplyAction= "http://tempuri.org/IInterBankOps/SellStockResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        void SellStock(string company, double amount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInterBankOpsChannel : Client.InterBank.IInterBankOps, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InterBankOpsClient : System.ServiceModel.ClientBase<Client.InterBank.IInterBankOps>, Client.InterBank.IInterBankOps {
        
        public InterBankOpsClient() {
        }
        
        public InterBankOpsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InterBankOpsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterBankOpsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterBankOpsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void PurchaseStock(string company, double amount) {
            base.Channel.PurchaseStock(company, amount);
        }
        
        public void SellStock(string company, double amount) {
            base.Channel.SellStock(company, amount);
        }
    }
}
