//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Server.Supervisor {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Supervisor.ISupervisorOps")]
    public interface ISupervisorOps {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISupervisorOps/PurchaseStock")]
        void PurchaseStock(int order_id,string company, int company_id, int quantity, string username, int client_id, DateTime request_date_time, string execution_value, string order_type);

 
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISupervisorOpsChannel : Server.Supervisor.ISupervisorOps, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SupervisorOpsClient : System.ServiceModel.ClientBase<Server.Supervisor.ISupervisorOps>, Server.Supervisor.ISupervisorOps {
        
        public SupervisorOpsClient() {
        }
        
        public SupervisorOpsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SupervisorOpsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupervisorOpsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupervisorOpsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }

        public void PurchaseStock(int id, string company,int company_id, int quantity, string username, int client_id, DateTime request_date_time, string execution_value, string order_type) {
            base.Channel.PurchaseStock(id,company,company_id, quantity, username, client_id, request_date_time, execution_value, order_type);
        }
    }
}
